# Generated by Django 4.2.2 on 2023-07-05 12:51

import datetime
from django.db import migrations, models
#


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 5, 18, 21, 10, 730899)),
        ),
    ]
