# Generated by Django 4.2.2 on 2023-07-06 17:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

#


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0002_alter_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 6, 23, 10, 39, 906699)),
        ),
        migrations.CreateModel(
            name='Withdrawstatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('utrno', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('IN PROCESS', 'IN PROCESS'), (
                    'REJECTED', 'REJECTED')], default='IN PROCESS', max_length=20)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depositstatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('utrno', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('IN PROCESS', 'IN PROCESS'), (
                    'REJECTED', 'REJECTED')], default='IN PROCESS', max_length=20)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
