# Generated by Django 4.2.2 on 2023-07-07 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0004_alter_user_created_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawstatement',
            name='utrno',
        ),
        migrations.AddField(
            model_name='withdrawstatement',
            name='upiid',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 18, 26, 54, 267854)),
        ),
    ]
