# Generated by Django 4.2.2 on 2023-07-07 13:08

import datetime
from django.db import migrations, models
import django.utils.timezone

#


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0005_remove_withdrawstatement_utrno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositstatement',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawstatement',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 7, 18, 37, 44, 29259)),
        ),
    ]
