# Generated by Django 4.2.2 on 2023-07-10 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0007_verifyotp_alter_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 11, 1, 22, 17, 772797)),
        ),
        migrations.AlterField(
            model_name='verifyotp',
            name='uid',
            field=models.CharField(
                default='<function uuid4 at 0x0000019F3B32A160>', max_length=200),
        ),
    ]
#
