# Generated by Django 4.2.2 on 2023-07-11 18:34

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0009_remove_verifyotp_uid_alter_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyotp',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 0, 3, 2, 802903)),
        ),
    ]
