# Generated by Django 4.2.2 on 2023-07-19 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0010_verifyotp_uid_alter_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 17, 28, 53, 432670)),
        ),
    ]
