# Generated by Django 4.2.2 on 2023-07-21 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0011_alter_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositstatement',
            name='utrno',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 13, 13, 42, 697503)),
        ),
        migrations.AlterField(
            model_name='withdrawstatement',
            name='upiid',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
