# Generated by Django 4.2.2 on 2023-07-21 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0013_alter_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawstatement',
            name='cause',
            field=models.CharField(default='Reviewing Request', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 14, 57, 4, 147069)),
        ),
    ]
